import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import Grid from '../components/Grid';
import { styled } from 'linaria/react';

const Screen = styled(Grid.Container)`
	background-color: #ff2dde;
	min-height: 100vh;
`;

const Home: NextPage = () => {
	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<Screen>
				<Grid.Item
					start={1}
					end={7}
					style={{ background: 'red', height: '100px' }}
				></Grid.Item>
			</Screen>
		</>
	);
};

export default Home;
