import type { NextPage } from 'next';
import * as Sections from '../sections';
import Head from 'next/head';
import { SectionSeparator } from '../components';
import Grid from '../components/Grid';
import { styled } from 'linaria/react';
import { theme } from '../styles/theme';

const Screen = styled(Grid.Container)`
	background-color: ${theme.colors.black};
	min-height: 100vh;
	padding: 12px;
`;

const Home: NextPage = () => {
	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<Screen as='main'>
				<Sections.About />
				<SectionSeparator>{'01. ACTOR'}</SectionSeparator>
				<Sections.Actor />
				<SectionSeparator>{'02. DIRECTOR OF ACTORS'}</SectionSeparator>
				<Sections.Director />
				<SectionSeparator>{'03. EDUCATOR OF OTHERS'}</SectionSeparator>
				<SectionSeparator>{'04. GALLERY'}</SectionSeparator>
				<SectionSeparator>{'05. CONTACT'}</SectionSeparator>
				<Sections.Contact />
			</Screen>
			<Sections.Footer />
		</>
	);
};

export default Home;
